providers: true
output:
  type: file
  dir: /repo/public
  basePath: '/composer-extdeps'
inputs:
  extdep:
    type: static
    packages:
      w8tcha/ckeditor-codemirror:
        v1.16:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/archive/1.16.tar.gz
          source:
            type: git
            url: https://github.com/w8tcha/CKEditor-CodeMirror-Plugin.git
            reference: '1.16'
      wet-boew/wet-boew:
        v4.0.27:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.27.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.27
        v4.0.28.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.28.1.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.28.1
        v4.0.29:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.29.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.29
        v4.0.30:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.30.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.30
        v4.0.31:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.31.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.31
        v4.0.32:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.32.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.32
        v4.0.33:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.33.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.33
        v4.0.34:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.34.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.34
        v4.0.35:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.35.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.35
        v4.0.38:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.38.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.38
        v4.0.39:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.39.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.39
        v4.0.39.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.39.1.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.39.1
        v4.0.40:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.40.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.40
        v4.0.41:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.41.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.41
        v4.0.42:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.42.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.42
        v4.0.42.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.42.1.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.42.1
        v4.0.42.2:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.42.2.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.42.2
        v4.0.43:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.43.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.43
        v4.0.43.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/wet-boew-cdn/archive/v4.0.43.1.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/wet-boew-cdn.git
            reference: v4.0.43.1
      wet-boew/theme-wet-boew:
        v4.0.27:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.27-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.27-theme-wet-boew
        v4.0.28.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.28.1-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.28.1-theme-wet-boew
        v4.0.29:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.29-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.29-theme-wet-boew
        v4.0.30:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.30-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.30-theme-wet-boew
        v4.0.31:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.31-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.31-theme-wet-boew
        v4.0.32:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.32-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.32-theme-wet-boew
        v4.0.33:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.33-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.33-theme-wet-boew
        v4.0.34:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.34-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.34-theme-wet-boew
        v4.0.35:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.35-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.35-theme-wet-boew
        v4.0.38:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.38-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.38-theme-wet-boew
        v4.0.39:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.39-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.39-theme-wet-boew
        v4.0.40:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.40-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.40-theme-wet-boew
        v4.0.41:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.41-theme-wet-boew.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.41-theme-wet-boew
      wet-boew/theme-base:
        v4.0.27:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.27-theme-base.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.27-theme-base
      wet-boew/theme-gc-intranet:
        v4.0.27:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.27-theme-gc-intranet.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.27-theme-gc-intranet
      wet-boew/theme-gcwu-fegc:
        v4.0.27:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.27-theme-gcwu-fegc.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.27-theme-gcwu-fegc
      wet-boew/theme-gcweb:
        v4.0.27:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.27-theme-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.27-gcweb
        v4.0.28.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.28.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.28.1-gcweb
        v4.0.29:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.29-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.29-gcweb
        v4.0.30:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/drupalwxt/themes-dist/releases/download/v4.0.30-gcweb/gcweb.tar.gz
          source:
            type: git
            url: https://github.com/drupalwxt/themes-dist.git
            reference: v4.0.30
        v5.0.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v5.0.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v5.0.1-gcweb
        v5.1.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v5.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v5.1-gcweb
        v6.0.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v6.0-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v6.0-gcweb
        v6.1.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v6.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v6.1-gcweb
        v7.0.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v7.0-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v7.0-gcweb
        v7.0.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v7.0.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v7.0.1-gcweb
        v8.0.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v8.0.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v8.0.1-gcweb
        v8.0.2:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v8.0.2-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v8.0.2-gcweb
        v8.1.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v8.1.0-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v8.1.0-gcweb
        v8.1.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v8.1.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v8.1.1-gcweb
        v9.0.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v9.0.0-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v9.0.0-gcweb
        v9.1.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v9.1.0-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v9.1.0-gcweb
        v9.2.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v9.2.0-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v9.2.0-gcweb
        v9.3.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v9.3.0-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v9.3.0-gcweb
        v9.4.0:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v9.4.0-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v9.4.0-gcweb
        v9.4.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v9.4.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v9.4.1-gcweb
      wet-boew/theme-gcweb-legacy:
        v4.0.27:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.27-theme-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.27-gcweb
        v4.0.28.1:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.28.1-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.28.1-gcweb
        v4.0.29:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.29-gcweb.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.29-gcweb
      wet-boew/theme-ogpl:
        v4.0.27:
          type: drupal-library
          dist:
            type: tar
            url: https://github.com/wet-boew/themes-cdn/archive/v4.0.27-theme-ogpl.tar.gz
          source:
            type: git
            url: https://github.com/wet-boew/themes-cdn.git
            reference: v4.0.27-theme-ogpl
